# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(745, 648)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 430, 591, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadbt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadbt.setObjectName("loadbt")
        self.horizontalLayout.addWidget(self.loadbt)
        self.startbt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startbt.setObjectName("startbt")
        self.horizontalLayout.addWidget(self.startbt)
        self.stopbt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopbt.setObjectName("stopbt")
        self.horizontalLayout.addWidget(self.stopbt)
        self.endbt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.endbt.setObjectName("endbt")
        self.horizontalLayout.addWidget(self.endbt)
        self.fpslcd = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.fpslcd.setObjectName("fpslcd")
        self.horizontalLayout.addWidget(self.fpslcd)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 591, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(620, 20, 111, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(51, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.selectcom = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.selectcom.setObjectName("selectcom")
        self.verticalLayout_2.addWidget(self.selectcom)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(61, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.selectbaud = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.selectbaud.setObjectName("selectbaud")
        self.selectbaud.addItem("")
        self.selectbaud.addItem("")
        self.selectbaud.addItem("")
        self.selectbaud.addItem("")
        self.verticalLayout_2.addWidget(self.selectbaud)
        self.openserial = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.openserial.setObjectName("openserial")
        self.verticalLayout_2.addWidget(self.openserial)
        self.closeserial = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.closeserial.setObjectName("closeserial")
        self.verticalLayout_2.addWidget(self.closeserial)
        self.serialshow = QtWidgets.QTextEdit(Form)
        self.serialshow.setGeometry(QtCore.QRect(20, 520, 591, 111))
        self.serialshow.setObjectName("serialshow")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loadbt.setText(_translate("Form", "打开"))
        self.startbt.setText(_translate("Form", "开始"))
        self.stopbt.setText(_translate("Form", "暂停"))
        self.endbt.setText(_translate("Form", "结束"))
        self.label.setText(_translate("Form", "播放区"))
        self.label_2.setText(_translate("Form", "选择串口"))
        self.label_3.setText(_translate("Form", "选择波特率"))
        self.selectbaud.setCurrentText(_translate("Form", "115200"))
        self.selectbaud.setItemText(0, _translate("Form", "115200"))
        self.selectbaud.setItemText(1, _translate("Form", "9600"))
        self.selectbaud.setItemText(2, _translate("Form", "38400"))
        self.selectbaud.setItemText(3, _translate("Form", "460800"))
        self.openserial.setText(_translate("Form", "打开串口"))
        self.closeserial.setText(_translate("Form", "关闭串口"))

